<?php defined('ABSPATH') || exit; $baseUrl = $page->url(); $today = $dashboard['1'] ?? ['orders'=>0,'revenue'=>0,'average'=>0]; $week = $dashboard['7'] ?? ['orders'=>0,'revenue'=>0,'average'=>0]; $month = $dashboard['30'] ?? ['orders'=>0,'revenue'=>0,'average'=>0]; ?>
<header class="fa-admin-welcome fa-oc-header"><div><h1 tabindex="-1">داشبورد مرکز سفارشات</h1><p>مدیریت سفارش‌های ووکامرس، وضعیت سفارش، مشتری، پرداخت، ارسال و آمار.</p></div><span class="fa-admin-build">HPOS Ready</span></header>
<?php if ($message = $page->queryString('fa_oc_success')) : ?><div class="notice notice-success"><p><?php echo esc_html($message); ?></p></div><?php endif; ?>
<?php if ($message = $page->queryString('fa_oc_error')) : ?><div class="notice notice-error"><p><?php echo esc_html($message); ?></p></div><?php endif; ?>
<section class="fa-oc-kpis" aria-label="آمار سفارش‌ها">
    <article class="fa-oc-kpi fa-oc-kpi--primary"><span>درآمد امروز</span><strong><?php echo wp_kses_post($page->money((float)$today['revenue'])); ?></strong><small><?php echo esc_html((string)$today['orders']); ?> سفارش</small></article>
    <article class="fa-oc-kpi"><span>۷ روز اخیر</span><strong><?php echo wp_kses_post($page->money((float)$week['revenue'])); ?></strong><small><?php echo esc_html((string)$week['orders']); ?> سفارش</small></article>
    <article class="fa-oc-kpi"><span>۳۰ روز اخیر</span><strong><?php echo wp_kses_post($page->money((float)$month['revenue'])); ?></strong><small><?php echo esc_html((string)$month['orders']); ?> سفارش</small></article>
    <article class="fa-oc-kpi"><span>میانگین سفارش</span><strong><?php echo wp_kses_post($page->money((float)$month['average'])); ?></strong><small>بر مبنای ۳۰ روز اخیر</small></article>
</section>
<section class="fa-oc-statuses" aria-label="وضعیت سفارش‌ها">
    <?php $currentStatus = $page->normalizeStatus($status); foreach ($statuses as $statusKey => $statusLabel) : $statusValue = $page->normalizeStatus((string)$statusKey); $selected = $currentStatus === $statusValue; ?><a class="fa-oc-status-card <?php echo esc_attr($page->statusClass($statusValue)); ?><?php echo $selected ? ' is-selected' : ''; ?>" href="<?php echo esc_url($selected ? $baseUrl : $page->url(['status'=>$statusValue])); ?>"><span><?php echo esc_html($statusLabel); ?></span><strong><?php echo esc_html((string)($statusCounts[$statusValue] ?? 0)); ?></strong></a><?php endforeach; ?>
</section>
<section class="fa-oc-panel">
    <form class="fa-oc-toolbar" method="get" action="<?php echo esc_url(admin_url('admin.php')); ?>"><input type="hidden" name="page" value="fa-order-center"><label class="screen-reader-text" for="fa-oc-search">جستجوی سفارش</label><input id="fa-oc-search" type="search" name="s" value="<?php echo esc_attr($search); ?>" placeholder="شماره سفارش، نام یا ایمیل مشتری…"><label class="screen-reader-text" for="fa-oc-status">فیلتر وضعیت</label><select id="fa-oc-status" name="status"><option value="">همه وضعیت‌ها</option><?php foreach ($statuses as $statusKey => $statusLabel) : $value = $page->normalizeStatus((string)$statusKey); ?><option value="<?php echo esc_attr($value); ?>" <?php selected($page->normalizeStatus($status), $value); ?>><?php echo esc_html($statusLabel); ?></option><?php endforeach; ?></select><button type="submit" class="button button-primary">جستجو</button><?php if ($search !== '' || $status !== '') : ?><a class="button" href="<?php echo esc_url($baseUrl); ?>">پاک‌کردن فیلتر</a><?php endif; ?></form>
    <div class="fa-oc-table-wrap"><table class="fa-oc-table"><thead><tr><th>سفارش</th><th>تاریخ</th><th>مشتری</th><th>محصولات</th><th>تعداد</th><th>جمع محصولات</th><th>تخفیف</th><th>ارسال</th><th>مالیات</th><th>مبلغ نهایی</th><th>پرداخت</th><th>وضعیت</th></tr></thead><tbody>
    <?php if ($result['orders'] === []) : ?><tr><td colspan="12" class="fa-oc-empty-cell">سفارشی با این مشخصات پیدا نشد.</td></tr><?php endif; ?>
    <?php foreach ($result['orders'] as $order) : if (! $order instanceof \WC_Order) { continue; } $customer = trim($order->get_formatted_billing_full_name()) ?: ($order->get_billing_email() ?: 'مهمان'); ?><tr><td data-label="سفارش"><a class="fa-oc-order-link" href="<?php echo esc_url($page->url(['order_id'=>$order->get_id()])); ?>">#<?php echo esc_html($order->get_order_number()); ?></a></td><td data-label="تاریخ"><?php echo esc_html($order->get_date_created() ? wc_format_datetime($order->get_date_created(), 'Y/m/d H:i') : '—'); ?></td><td data-label="مشتری"><strong><?php echo esc_html($customer); ?></strong><small><?php echo esc_html($order->get_billing_phone()); ?></small></td><td data-label="محصولات"><?php echo wp_kses_post($page->orderItemsSummary($order)); ?></td><td data-label="تعداد"><?php echo esc_html((string)$order->get_item_count()); ?></td><td data-label="جمع محصولات"><?php echo wp_kses_post($page->money((float)$order->get_subtotal(), $order->get_currency())); ?></td><td data-label="تخفیف"><?php echo wp_kses_post($page->money((float)$order->get_discount_total(), $order->get_currency())); ?></td><td data-label="ارسال"><?php echo wp_kses_post($page->money((float)$order->get_shipping_total(), $order->get_currency())); ?></td><td data-label="مالیات"><?php echo wp_kses_post($page->money((float)$order->get_total_tax(), $order->get_currency())); ?></td><td data-label="مبلغ نهایی"><strong><?php echo wp_kses_post($order->get_formatted_order_total()); ?></strong></td><td data-label="پرداخت"><?php echo esc_html($order->get_payment_method_title() ?: '—'); ?></td><td data-label="وضعیت"><span class="fa-oc-status <?php echo esc_attr($page->statusClass($order->get_status())); ?>"><?php echo esc_html($page->statusLabel($order->get_status())); ?></span></td></tr><?php endforeach; ?></tbody></table></div>
    <?php if ($result['pages'] > 1) : ?><nav class="fa-oc-pagination" aria-label="صفحات سفارش‌ها"><?php echo wp_kses_post(paginate_links(['base'=>add_query_arg(['page'=>'fa-order-center','paged'=>'%#%','s'=>$search,'status'=>$status], admin_url('admin.php')),'format'=>'','current'=>$result['page'],'total'=>$result['pages'],'type'=>'list','prev_text'=>'قبلی','next_text'=>'بعدی'])); ?></nav><?php endif; ?>
</section>
